#host settings
#Tue Sep 27 20:01:39 CEST 2022
usedNetworkInterface=eth2 | 192.168.112.83
xsplitPort=8889
FlowEditorHeight=667.0
language=en-EN
collapsedActions=011000000000000
connectionPort=12134
useDeviceLastHeight=1080
startupTutorialStep=12
obsAutoConnect=false
FlowEditorWidth=1142.0
connectionPortOutGoing=12135
firstTimeClose=false
autoCreateBackButtons=false
TouchButtonWidth=1142.0
betacode=1
TWITCH_CHATTOKEN=
slobsAutoConnect=false
isSecured=false
startAtBootMinimized=false
connectionPortUSB=13145
useDeviceLastWidth=1920
obsWebsocketPassword=
obsWebsocketPort=4444
obsWebsocketIp=localhost
buttonDetailTutorialStep=9
startAtBoot=false
lastUsedIconPack=Flat White Icon pack
lastConnectedIp=192.168.112.83
TouchButtonHeight=668.0
firstTimeStart=false
Category_visibilities=
useDeviceForPreview=true
doNotCheckFirewall=false
TWITCH_ACCESSTOKEN=
firstTimeNewVersion=301005
